# Generated by Django 3.2.12 on 2022-07-12 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_shown',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='viewable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='converted_image',
            field=models.ImageField(editable=False, upload_to='./converted_images'),
        ),
    ]
